services:
  profile-managment-service:
    image: openjdk:22-jdk-oracle
    container_name: profileimage
    ports:
      - "${SERVICE_PORT1}:8080"
      - "${SERVICE_PORT2}:8000"
    depends_on:
      - profile-db
    networks:
      - greenspot-net
    volumes:
      - ./build/libs/ProfileManagmentService-v0.0.0.jar:/app/app.jar
    working_dir: /app
    entrypoint: java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -jar /app/app.jar

  profile-db:
    image: mongo:latest
    container_name: profiledb
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_profile:/etc/mongo
      - mongo_profile_data:/data/db
      - mongo_profile_config:/data/configdb
    networks:
      - greenspot-net

networks:
  greenspot-net:
    name: greenspot_net

volumes:
  mongo_profile:
  mongo_profile_data:
  mongo_profile_config: